### PR TITLE
Make it fully `no_std`

### PR DESCRIPTION
**Pull request by 1tgr**
- Opt out of all default features in dependencies
- Don't `extern crate std;`

### CODE REVIEW

**Comment by bschwind** [comment]
Hi @1tgr , thanks for the PR! This is my first `no_std` crate so I wasn't sure of the right way to include tests which use the standard library. Seems it's still failing on that step.

**Comment by 1tgr** [comment]
Fixed, sorry about that!

**Comment by bschwind** [comment]
No worries at all, thanks again!

Out of curiosity, what's your use case for this crate? I originally created it for the emoji PNG decoder for [fontdue](https://crates.io/crates/fontdue) but it's still not as competitive performance-wise with the `image` crate.

**Comment by 1tgr** [comment]
It’s for this operating system project:
https://github.com/1tgr/rust-os/

As the standard`std` doesn’t support my OS, it’s easier to select `no_std` crates, or crates that can easily be made `no_std`. Here I wanted to `include_bytes!` a .png file representing a mouse pointer.

**Comment by bschwind** [comment]
Ahhh that's great! Please let me know if you run into any other issues.

**Pull request merged**
